[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.egg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | _build
  | \.venv
  | src
  | bin
  | stream_chat\.egg-info
  | fabfile.py
  | lib
  | docs
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
src_paths = ["stream_chat"]
known_first_party = ["stream_chat"]

[tool.pytest.ini_options]
testpaths = ["stream_chat/tests"]
asyncio_mode = "auto"

[tool.mypy]
disallow_untyped_defs = true
disallow_untyped_calls = true
check_untyped_defs = true
warn_unused_configs = true
strict_optional = false

[[tool.mypy.overrides]]
module = "stream_chat.tests.*"
ignore_errors = true