__author__ = "Tommaso Barbugli"
__copyright__ = "Copyright 2019, Stream.io, Inc"
__license__ = "To be defined"
__version__ = "0.0.1"
__maintainer__ = "Tommaso Barbugli"
__email__ = "support@getstream.io"
__status__ = "Production"
