__author__ = "Tommaso Barbugli"
__copyright__ = "Copyright 2019-2020, Stream.io, Inc"
__version__ = "3.0.1"
__maintainer__ = "Tommaso Barbugli"
__email__ = "support@getstream.io"
__status__ = "Production"
