__author__ = "Tommaso Barbugli"
__copyright__ = "Copyright 2019, Stream.io, Inc"
__version__ = "1.0.2"
__maintainer__ = "Tommaso Barbugli"
__email__ = "support@getstream.io"
__status__ = "Production"
